spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.jpmc.midascore.kafka.serializer.TransactionSerializer
    consumer:
      group-id: midas-core-transaction-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.jpmc.midascore.kafka.serializer.TransactionDeserializer
      auto-offset-reset: earliest

general:
  kafka-topic: my-test-topic